apiVersion: apps/v1
kind: Deployment
metadata:
  name: llamacpp
  namespace: llama-app
  labels:
    app: llamacpp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: llamacpp
  template:
    metadata:
      labels:
        app: llamacpp
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8083"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: llamacpp
        image: DOCKER_HUB_USERNAME/llamacpp-server:IMAGE_TAG
        ports:
        - containerPort: 8083
          name: http
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
        env:
        - name: LLAMA_THREADS
          value: "4"
        livenessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 10
          periodSeconds: 5
        volumeMounts:
        - name: models
          mountPath: /models
        - name: config
          mountPath: /config
      volumes:
      - name: models
        emptyDir: {}
      - name: config
        configMap:
          name: llamacpp-config