kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30083
    hostPort: 8084
  - containerPort: 30090
    hostPort: 9090
  - containerPort: 30030
    hostPort: 3001
