apiVersion: apps/v1
kind: Deployment
metadata:
  name: llamacpp
  namespace: llama-app
  labels:
    app: llamacpp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llamacpp
  template:
    metadata:
      labels:
        app: llamacpp
    spec:
      containers:
      - name: llamacpp-server
        image: DOCKER_HUB_USERNAME/llamacpp-server:IMAGE_TAG
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PORT
          value: "8080"
        - name: HOST
          value: "0.0.0.0"
        # Temporarily disable resource limits for debugging
        # resources:
        #   requests:
        #     memory: "512Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "2Gi"
        #     cpu: "1000m"
        # Temporarily disable health checks for debugging
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8080
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8080
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
        volumeMounts:
        - name: config
          mountPath: /app/config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: llamacpp-config